apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: envoy-pilot-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-pilot-server
  template:
    metadata:
      labels:
        app: envoy-pilot-server
    spec:
      volumes:
        - name: pilot-config-volume
          configMap:
            name: pilot-configmap
            items:
              - key: pilot-config
                path: .env
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 7777
            - name: http
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          volumeMounts:
            - name: pilot-config-volume
              mountPath: /.env
              subPath: .env
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pilot-configmap
  namespace: {{ .Values.namespace }}
data:
  pilot-config: |-
    CONSUL_PATH: {{ .Values.config.CONSUL_PATH }}